# Generated by Django 3.2 on 2021-04-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_review_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='heading',
        ),
        migrations.AddField(
            model_name='review',
            name='occupation',
            field=models.CharField(default='', max_length=254),
        ),
    ]
