# Generated by Django 3.2 on 2021-04-29 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TutoringRates',
            new_name='TutoringRate',
        ),
    ]
